### ISSUE TITLE
Baseline: EncT5

### ISSUE THREAD

**Issue by bclavie** [AnswerDotAI/bert24#12]

**Comment by raphaelsty** [comment]
I would be happy to contribute on this one which seems great to start with !

Don't hesitate to tell me if I'm going the wrong way:

- We would add an extra argument namely T5 to the function `build_model` of `glue.py` script and create a dedicated `t5_module.create_t5_classification`. 

- I have found a reference code available at [t5-fine-tuning]( https://colab.research.google.com/github/patil-suraj/exploring-T5/blob/master/t5_fine_tuning.ipynb#scrollTo=0B4IhzEgO21B), would it be consistent with building a Baseline EnCT5?

**Comment by bclavie** [comment]
Hey @raphaelsty ! Yes, @NohTow is correct, this is about setting up baselines with only the Encoder + the EncT5 recipe for:
- PileT5-base
- T51.1-large (there's an unknown issue with PileT5-large where it performs surprisingly weakly)
- PileT5-XL
To serve as a very strong comparison point for our own base/large/XL variants.
