### ISSUE TITLE
Arch: RoPE instead of ALiBi

### ISSUE THREAD

**Issue by bclavie** [AnswerDotAI/bert24#3]
The repository is currently using the [unpadding trick](https://arxiv.org/abs/2208.08124) to reduce wasted compute, so adding RoPE is not as straightforward as it'd normally be, since it must be implemented in a way that'll keep track of where each sequence ends and begins.

**Comment by bclavie** [comment]
@staghado, I hear you're interested in this one 👀 ?

**Comment by staghado** [comment]
Sure, I can take a stab at it.
