### ISSUE TITLE
Migrate ColBERT to conda environment to leverage faiss-gpu

### ISSUE THREAD

**Issue by bclavie** [AnswerDotAI/bert24#37]
Follow-up to #29. `faiss-gpu` currently cannot be installed via pip, which will cause evals to take an unnecessarily long time. We should make sure faiss-gpu can be added as seamlessly as possible to the conda env.

**Comment by NohTow** [comment]
Could we add something like 
```
{% if ColBERTL|default('false')|lower == 'true' %}
    - faiss-gpu
{% endif %}
```
To the environment.yml
And use `ColBERT=true conda env create --file environment.yml` to install the env?
